### PR TITLE
Updated flash messages for app.

### PR DESCRIPTION
**Pull request by ritik-bluebash**
Updated flash messages for whole app.

**1. Homepage flash message position**
https://user-images.githubusercontent.com/80153678/152789631-2a46885b-7159-4250-bad4-064b789ce5c0.mp4

**2. Show page flash message position.**
https://user-images.githubusercontent.com/80153678/152789660-9de67253-86ad-4190-8b79-36c8a4f91d14.mp4

### CODE REVIEW

**Comment by vishal-bluebash** [comment]
@ritik-bluebash How about error messages

**Review by vishal-bluebash — APPROVED** [review]

**Comment by ritik-bluebash** [comment]
Hello @duarme @ValerioVillani @vishal-bluebash 
Please check the videos in this PR's description. Merged this PR on staging to test new flash messages (https://publicv-staging.herokuapp.com)
I have used bootstrap alerts. Also added auto fading to alerts.

Let me know if any changes required in flash messages..

**Comment by ValerioVillani** [comment]
@bb-nikita the sign in message is fine, 

the sign up instead it's a bit too long.


image


Let's try just this:

Welcome on uCV! We have sent you an email to confirm your account!

**Comment by ritik-bluebash** [comment]
Hello @ValerioVillani 
Welcome on uCV! We have sent you an email to confirm your account!

Can you send me an italian copy for this?

**Comment by ValerioVillani** [comment]
@ritik-bluebash 

Italian:

Benvenuto su uCV! Ti abbiamo inviato una email per confermare il tuo account!

**Comment by duarme** [comment]
@ritik-bluebash did you add this translation to the codebase? I cannot find any .yml file inside this PR:

> Benvenuto su uCV! Ti abbiamo inviato una email per confermare il tuo account!

**Pull request merged**
