### PR TITLE
Improved search page card

### PR DESCRIPTION
**Pull request by ritik-bluebash**
Issue:- #297 
Improved search page card
Screenshot from 2022-01-28 13-15-21

### CODE REVIEW

**Comment by ValerioVillani** [comment]
@ritik-bluebash The idea is that, Perfect. 
Give me just a few days to create a Graphic Sample, right now it's a bit ugly.

I will change it in Hold.

**Comment by ValerioVillani** [comment]
Hi @ritik-bluebash and @bb-nikita Let's check this out

Name
!

- If the bio sentence is too long, we will cut it at some point and add ".."
- If there are too many skills, for the moment, we will prioritize the first 4 they write down in the " Working Skill" Box. Then we will fix this giving them the possibility to customize the skills that they insert into the card. 

How does it look?

**Comment by duarme** [comment]
@ValerioVillani @ritik-bluebash I'd avoid labels, or at least shorten them, every time it's possible. How about:

CleanShot 2022-01-28 at 09 03 06@2x

**Comment by bb-nikita** [comment]
Hi @duarme . I agree with the idea but instead of **available in** we can use another term. How about "**Join in"**. **Available in** is somewhat relating to a product rather than candidates.

What say @ValerioVillani .

**Comment by ValerioVillani** [comment]
@bb-nikita It's super okay, I used labels to make it more clear in my mind, but we definitely can remove them :))

**Comment by ValerioVillani** [comment]
@bb-nikita We can implement Duccio's corrections and also go with "Join in" correction (as you suggested :)) 

Lets try also a "darker" gray.

This is a really important feature, let's try to give it a good look.

**Comment by ritik-bluebash** [comment]
Hello @ValerioVillani @duarme @vishal-bluebash, 
As suggested above, i removed the labels from SERP CV cards. but there cant be clear segregation between CV skills and bio.

Screenshot from 2022-02-08 17-11-45

My suggestion is that we should keep labels (but in light colours) so that anyone who searches should be clear about what details are being displayed on the resulting cards. 
Also, we will not display labels if there wont be any detail present corresponding to that label.

Like this:
Screenshot from 2022-02-08 17-16-59

How about this?

**Comment by ValerioVillani** [comment]
@ritik-bluebash 
Good call Ritik. we can:

- keep this:
Cattura

- As a lebel we'll use just "Skills", "Salary" and "Join in" (instead of available in).

From an UI point of You, we can for sure use different colour or maybe try to adapt the new Primary colour scheme: #361

**Comment by ritik-bluebash** [comment]
@ValerioVillani 
Updated the card to this.
Please check and let me know if any change required.

Screenshot from 2022-02-09 14-03-17

**Comment by ValerioVillani** [comment]
@ritik-bluebash If we remove the underline it's perfect! Great Job!

**Pull request merged**
