### PR TITLE
Passwordless User

### PR DESCRIPTION
**Pull request by ritik-bluebash**
Issue:- #234 

**1. Passwordless Sign Up**
https://user-images.githubusercontent.com/80153678/147655733-6e8f773c-cebf-4748-83ad-a7bc248d0293.mp4

**2. Passwordless sign_in and sign_out**
https://user-images.githubusercontent.com/80153678/147655795-35c3f0a5-7d3f-485c-8f16-61ea647ba49d.mp4

**3. Passwordless Confirmation Instructions**
https://user-images.githubusercontent.com/80153678/147655850-f0c2f378-1ab2-4a75-861f-b62fb85ad11c.mp4

**4. Passwordless Email and subdomain Update** 
https://user-images.githubusercontent.com/80153678/147655904-10357aa9-14af-4cbd-a03b-0af033fbb0be.mp4

### CODE REVIEW

**Comment by duarme** [comment]
Hello @ritik-bluebash when this is ready please remember to ask for my review too :)

**Comment by vishal-bluebash** [comment]
@ritik-bluebash can you rebase and add demo on this

**Comment by vishal-bluebash** [comment]
@duarme @ValerioVillani We need copy for emails on this feature

**Comment by ValerioVillani** [comment]
> @duarme @ValerioVillani We need copy for emails on this feature

Goodevening @vishal-bluebash, Do we need a copy to share with users this new feature or to inform them every time they changed their subdomain?

**Comment by vishal-bluebash** [comment]
> > @duarme @ValerioVillani We need copy for emails on this feature
> 
> Goodevening @vishal-bluebash, Do we need a copy to share with users this new feature or to inform them every time they changed their subdomain?

I will explain you over our meeting

**Comment by ValerioVillani** [comment]
@vishal-bluebash @bb-nikita @ritik-bluebash 
Italian translation done! Sorry for the wait.

**Review by vishal-bluebash — APPROVED** [review]

**Pull request merged**
